name: GITHUB_OUTPUT
run-name: Run by @${{ github.actor }}
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - name: github output env
        id: source
        run: echo "result=Hello" >> ${GITHUB_OUTPUT}
        env: 
          RESULT: ${{ steps.source.output.result }}
      - name: echo env
        run: echo ${RESULT}