name: Secrets
on: push
jobs:
    print:
        runs-on: ubuntu-latest
        env:
            PASSWORD: ${{secrets.PASSWORD}}
            PASSWORD_GH: ${{secrets.PASSWORD_GH}}
        steps:
            - run: echo "${PASSWORD}"
            - run: echo "${PASSWORD_GH}"